// Portal impersonation: a short-lived one-time link that signs the browser in to the web portal as an investor
// or a distributor. Generated by the backoffice (dashboard POST, portfolio/performance POST, bo/impersonate)
// and by the distributor portal (/api/distributor/view-investor, a partner opening one of their investors).
//
// The link carries a JWT signed with JWT_SECRET (`kind: 'imp'`, 2 min). /api/admin/impersonate verifies it,
// refuses anything older than 5 minutes or already used, sets the portal cookies (including the signed
// `qode-session`) and writes an audit row naming who opened it (`by`, inside the signed token).
import crypto from 'crypto'
import jwt from 'jsonwebtoken'
import { query } from '@/lib/db'

export const IMP_TOKEN_TTL = 120          // seconds, the life of a freshly issued link
export const IMP_TOKEN_MAX_AGE = 5 * 60   // seconds, hard ceiling checked on use

export type ImpClientData = { clientid: string | null; clientcode: string | null }

export type ImpPayload = {
  kind: 'imp'
  jti: string
  /** Email of whoever generated the link: a backoffice admin, or a distributor viewing their investor. */
  by: string
  via: 'admin' | 'distributor'
  clientCode: string | null
  clientType?: 'DISTRIBUTORS'
  clientData: ImpClientData[]
  userContext: {
    clientid: string | null
    clientcode: string | null
    email: string | null
    groupid: string | null
    head_of_family: boolean
    ownerid: string | null
  }
  targetClientName: string
}

export type PortalImpersonation = {
  token: string
  redirectUrl: string
  clientData: ImpClientData[]
  isHeadOfFamily: boolean
  targetClientName: string
  targetEmail: string | null
}

const fullName = (r: any) => `${r.salutation || ''} ${r.firstname} ${r.middlename || ''} ${r.lastname}`.trim()

function sign(p: Omit<ImpPayload, 'kind' | 'jti'>): string {
  const payload: ImpPayload = { kind: 'imp', jti: crypto.randomUUID(), ...p }
  return jwt.sign(payload, process.env.JWT_SECRET!, { expiresIn: IMP_TOKEN_TTL })
}

/** Verifies a portal impersonation token. Returns the payload, or an error message. */
export function verifyImpersonationToken(token: string): { payload?: ImpPayload & { iat: number }; error?: string } {
  try {
    const p = jwt.verify(token, process.env.JWT_SECRET!) as any
    if (p?.kind !== 'imp' || !p.by || !p.jti || !Array.isArray(p.clientData) || !p.userContext) return { error: 'Invalid impersonation token' }
    if (!p.iat || Date.now() / 1000 - p.iat > IMP_TOKEN_MAX_AGE) return { error: 'Impersonation token expired' }
    return { payload: p }
  } catch (e: any) {
    return { error: e?.name === 'TokenExpiredError' ? 'Impersonation token expired' : 'Invalid impersonation token' }
  }
}

const link = (token: string) => `/api/admin/impersonate?token=${encodeURIComponent(token)}`

/**
 * Investor portal link by client code (the same account set the admin dashboard always used: the whole group
 * for a head of family, otherwise the owner's accounts). Null when the code is unknown.
 */
export async function investorPortalImpersonation(clientCode: string, by: string, via: ImpPayload['via'] = 'admin'): Promise<PortalImpersonation | null> {
  const clientResult = await query(
    `SELECT clientid, clientcode, email, groupid, head_of_family, ownerid,
            salutation, firstname, middlename, lastname
       FROM pms_clients_master
      WHERE clientcode = $1`,
    [clientCode],
  )
  if (clientResult.rows.length === 0) return null
  const t = clientResult.rows[0]

  const associated = t.head_of_family
    ? await query('SELECT clientid, clientcode FROM pms_clients_master WHERE groupid = $1', [t.groupid])
    : await query('SELECT clientid, clientcode FROM pms_clients_master WHERE ownerid = $1', [t.ownerid])
  const clientData: ImpClientData[] = associated.rows.map((r: any) => ({ clientid: r.clientid, clientcode: r.clientcode }))
  const targetClientName = fullName(t)

  const token = sign({
    by, via, clientCode, clientData, targetClientName,
    userContext: {
      clientid: t.clientid, clientcode: t.clientcode, email: t.email, groupid: t.groupid,
      head_of_family: !!t.head_of_family, ownerid: t.ownerid,
    },
  })
  return { token, redirectUrl: link(token), clientData, isHeadOfFamily: !!t.head_of_family, targetClientName, targetEmail: t.email }
}

/** Distributor portal link by login email. Null when no distributor row has that email. */
export async function distributorPortalImpersonation(email: string, by: string): Promise<PortalImpersonation | null> {
  const r = await query(
    `SELECT clientid, clientcode, email, groupid, head_of_family, ownerid,
            salutation, firstname, middlename, lastname, clienttype
       FROM pms_clients_master
      WHERE lower(email) = lower($1) AND (clienttype = 'DISTRIBUTORS' OR clientcode IS NULL)
      ORDER BY (clientcode IS NULL) DESC
      LIMIT 1`,
    [String(email).trim()],
  )
  if (r.rows.length === 0) return null
  const d = r.rows[0]
  // clientData mirrors a real distributor login: clientid present, clientcode may be null.
  const clientData: ImpClientData[] = [{ clientid: d.clientid, clientcode: d.clientcode }]
  const targetClientName = fullName(d)
  const token = sign({
    by, via: 'admin', clientCode: d.clientcode, clientType: 'DISTRIBUTORS', clientData, targetClientName,
    userContext: {
      clientid: d.clientid, clientcode: d.clientcode, email: d.email, groupid: d.groupid,
      head_of_family: false, ownerid: d.ownerid,
    },
  })
  return { token, redirectUrl: link(token), clientData, isHeadOfFamily: false, targetClientName, targetEmail: d.email }
}
